[build]
  base = "."
  publish = "packages/client/dist"
  command = "pnpm install && pnpm build"

[build.environment]
  NODE_VERSION = "18"
  VITE_SERVER_URL = "https://artmak-production.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
